### ISSUE TITLE
Unclear binding usage of TradewindsMove

### ISSUE THREAD

**Issue by cookiengineer** [andymass/vim-tradewinds#1]
For me, it was unclear how to use the `TradewindsMove` command directly, so that I can also use arrow keys as I would expect them to behave.

So I created a pull request: https://github.com/andymass/vim-tradewinds/pull/2

This will only modify the `README.md` to include a more detailed example that reuses the `TradewindsMove` method directly - so that users know that they can also use complex custom bindings or shortcuts on their own.

**Comment by andymass** [comment]
I'm just curious, what is the reason you want to map to the `TradewindsMove` command rather than the `<plug>(tradewinds-h)` maps?  You could `nmap <left> <plug>(tradewinds-h)` for example (in this respect I noticed a bug in the documentation, whoops).

**Comment by cookiengineer** [comment]
I dunno, I guess it was much easier for me to figure out how it works, as I tried out what happened with `:t<tab>` and `:Trade<tab>` while editing the vim config etc... and I found [the method](https://github.com/andymass/vim-tradewinds/blob/master/plugin/tradewinds.vim#L21) and was assuming that it's meant for public usage due to its Camel style name, I guess.

**Comment by andymass** [comment]
Ah, got it.  Agreed it should be mentioned.
